### ISSUE TITLE
Error "unhashable type: 'dict'" during tag update with Netbox >= 2.9.0

### ISSUE THREAD

**Issue by akovan** [digitalocean/pynetbox#289]
Hi,

I'm trying to use pynetbox with Netbox 2.9.3 and faced with an issue during update procedure. Here's sample of code:
```
update_address = nb.ipam.ip_addresses.get(id) 
update_address.update(dict(
    tags = [dict(name = tag)]
))
```
and I have the following error:
```
Traceback (most recent call last):
  File "/home/car/git/test/test.py", line 21, in <module>
    tags = [dict(name = tag)]
  File "/home/car/git/test/.venv/lib/python3.6/site-packages/pynetbox/core/response.py", line 419, in update
    return self.save()
  File "/home/car/git/test/.venv/lib/python3.6/site-packages/pynetbox/core/response.py", line 381, in save
    diff = self._diff()
  File "/home/car/git/test/.venv/lib/python3.6/site-packages/pynetbox/core/response.py", line 357, in _diff
    current = Hashabledict({fmt_dict(k, v) for k, v in self.serialize().items()})
  File "/home/car/git/test/.venv/lib/python3.6/site-packages/pynetbox/core/response.py", line 345, in serialize
    current_val = list(OrderedDict.fromkeys(current_val))
TypeError: unhashable type: 'dict'
```
I can create objects with tags without problems, but update does not work

pynetbox version: 5.0.8
Netbox version: 2.9.3
python version 3.6.9

**Comment by jmcguir** [comment]
I can put in a pull request but it seems like the direct fix is to remove tags from LIST_AS_SET Constant.  

Here is some sample code that works for me. 

      device = nb.dcim.devices.get(name=hostname)
      new_tag = {'name': 'example_tag'}
      device.tags.append(new_tag)
      device.update({"tags": device.tags})

**Comment by tomneedham** [comment]
Fixed in https://github.com/digitalocean/pynetbox/pull/291

**Comment by pijav** [comment]
Hello!

Was that really fixed for ip_addresses?

```
ip = "10.3.5.14"
ip_address = nb.ipam.ip_addresses.get(q=ip+"/")

tag = {'name': 'some_tag'}
ip_address.tags.append({"name": tag})

ip_address.update({"tags": ip_address.tags})
```

```
File "C:\Program Files (x86)\Software\venv\lib\site-packages\pynetbox\core\response.py", line 345, in serialize
    current_val = list(OrderedDict.fromkeys(current_val))
TypeError: unhashable type: 'dict'
```

**Comment by ravenrs** [comment]
Hello,
Does anyone have any news about this bug? it still doesn't work with netbox 2.9.7.
